In [7]:
# Задание3
from scipy.optimize import minimize
import numpy as np

In [8]:
#Объявляем функцию
def objectiv(x):
    x1=x[0]
    x2=x[1]
    x3=x[2]
    x4=x[3]
    return x1*x4*(x1+x2+x3)+x3
def constraint1(x):
    return x[0]*x[1]*x[2]*x[3]-25.0
def constraint2(x):
    sum_sqr=40
    for i in range(4):
        sum_sqr=sum_sqr-x[i]**2
    return sum_sqr


In [53]:
#Начальная точка
x0=[1,5,5,1]


In [10]:
#Ограничения
b=[1.0,5.0]
bnds=[b,b,b,b]
con1={'type':'ineq','fun':constraint1}
con2={'type':'eq','fun':constraint2}
cons=[con1,con2]


In [11]:
# Якобиан
def der(x):
    return np.array([2*x[0]*x[3]+x[3]*x[1]+x[3]*x[2],x[0]*x[3],x[0]*x[3]+1,x[0]**2+x[0]*x[1]])

In [30]:
#Гессиан
def der2(x):
    return np.array([2*x[3],0,0,0])

In [44]:
sol1=minimize(objectiv,x0,method='SLSQP',jac=der,bounds=bnds,constraints=cons)

In [47]:
sol2=minimize(objectiv,x0,method='CG',jac=der,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method CG cannot handle constraints nor bounds.
  RuntimeWarning)


In [16]:
sol3=minimize(objectiv,x0,method='BFGS',jac=der,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method BFGS cannot handle constraints nor bounds.
  RuntimeWarning)


In [18]:
sol4=minimize(objectiv,x0,method='Newton-CG',jac=der,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method Newton-CG cannot handle constraints nor bounds.
  RuntimeWarning)


In [20]:
sol5=minimize(objectiv,x0,method='L-BFGS-B',jac=der,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:397: RuntimeWarning: Method L-BFGS-B cannot handle constraints.
  RuntimeWarning)


In [22]:
sol6=minimize(objectiv,x0,method='TNC',jac=der,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:397: RuntimeWarning: Method TNC cannot handle constraints.
  RuntimeWarning)


In [38]:
sol7=minimize(objectiv,x0,method='Nelder-Mead',jac=der,hess=der2,bounds=bnds,constraints=cons)

C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:381: RuntimeWarning: Method Nelder-Mead does not use gradient information (jac).
  RuntimeWarning)
C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:385: RuntimeWarning: Method Nelder-Mead does not use Hessian information (hess).
  RuntimeWarning)
C:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py:394: RuntimeWarning: Method Nelder-Mead cannot handle constraints nor bounds.
  RuntimeWarning)


In [52]:
# Лучший способ
sol6

     fun: 4.0
     jac: array([ 4.,  1.,  2.,  2.])
 message: 'Local minimum reached (|pg| ~= 0)'
    nfev: 5
     nit: 2
  status: 0
 success: True
       x: array([ 1.,  1.,  1.,  1.])

In [193]:
#Задание2
import numpy as np
nrows=5
ncols=5
def gtt(nrows,ncols):
    a = np.random.randint(100, size=(nrows,ncols))
    for i in range(ncols-1):
        for j in range(nrows-i-1):
            a[i+j+1]=a[i+j+1]-a[i]*(a[i+j+1][i]/a[i][i])
   
    return a
tt=gtt(nrows,ncols)
rang=0
for i in range(nrows):
    if tt[i][i]>0 or tt[i][i]<0:
        rang=rang+1

tt


array([[  51,   97,   50,   73,   21],
       [   0,   20,    6,   56,   46],
       [   0,    0,  -39,  191,  252],
       [   0,    0,    0, -161,  -99],
       [   0,    0,    0,    0,  -32]])

In [194]:
rang

5

In [215]:
#Задание1
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
a=[]
oo=np.array(Z)
p=[1,2,3,4]
for i in range(len(Z)):
    b=Z[i:i+4]
    if len(b)==4:
        a.append(b)
print(np.array(a))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
